name: Run single Supabase migration

on:
  workflow_dispatch:
    inputs:
      migration_file:
        description: "Path to SQL file. Example: supabase/migrations/20251030121000_add_users.sql"
        required: true
      database_url:
        description: "Optional DB URL override"
        required: false
        default: ""

jobs:
  run-one:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ github.event.inputs.database_url != '' && github.event.inputs.database_url || secrets.SUPABASE_DB_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Execute migration
        run: |
          FILE="${{ github.event.inputs.migration_file }}"
          if [ ! -f "$FILE" ]; then
            echo "File not found: $FILE"
            exit 1
          fi

          supabase db execute \
            --file "$FILE" \
            --db-url "$SUPABASE_DB_URL"
