name: Supabase migrations

on:
  push:
    paths:
      - "supabase/**"
      - ".github/workflows/supabase-migrations.yml"
  pull_request:
    paths:
      - "supabase/**"

jobs:
  migrations:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Ensure migrations dir
        run: mkdir -p supabase/migrations

      - name: Run migrations on CI db
        run: |
          supabase db push \
            --db-url "$SUPABASE_DB_URL"
